#!/bin/bash
#docker install
set -e
sudo apt update
sudo apt install ca-certificates curl gnupg -y
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg

echo \
"deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
"$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt update
sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo usermod -aG docker $USER
newgrp docker
echo Done docker
echo ""
echo "try docker version"
echo "sudo systemctl status docker"
echo "docker run hello-world"

#time sudo docker pull ollama/ollama:latest
#echo "Latest docker ollama installed"
#time sudo docker pull ollama/ollama:0.1.27-rocm
#echo "Version 0.1.27 ROCm docker installed"
#echo "Running AMDGPU ready ollama docker"
#time sudo docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama -e HSA_OVERRIDE_GFX_VERSION='10.3.0' --group-add=video --ipc=host --privileged --cap-add=SYS_PTRACE --security-opt seccomp=unconfined ollama/ollama:0.1.27-rocm
#echo "docker exec -it ollama ollama run MODEL_HERE"
#sudo docker exec -it ollama ollama run tinyllama --verbose
echo "Done Dockering"
#EOF
